[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'neomru.vim'
hook_post_source = '''
" Ag command on grep source
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts',
        \ ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
" Ag command on file_rec source
call denite#custom#var('file_rec', 'command',  ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#map('insert', "<C-n>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-p>", '<denite:move_to_previous_line>')
call denite#custom#map('insert', "<C-a>", '<denite:move_caret_to_head>')
call denite#custom#map('insert', "jj", '<denite:enter_mode:normal>')
'''
hook_add = '''
nmap <silent> ,uf :<C-u>DeniteProjectDir file_rec<CR>
nmap <silent> ,ug :<C-u>Denite grep<CR>
nmap <silent> ,uu :<C-u>Denite buffer file_mru<CR>
nmap <silent> ,uh :<C-u>Denite help<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ["python", "python3", "djangohtml"]
hook_add = '''
  let g:jedi#completions_enabled = 0
'''

[[plugins]]
repo = 'lambdalisue/vim-pyenv' 
depends = ['davidhalter/jedi-vim']

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'ompugao/ros.vim'
