[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ["python", "python3", "djangohtml"]
hook_add = '''
  let g:jedi#completions_enabled = 0
'''

[[plugins]]
repo = 'lambdalisue/vim-pyenv' 
depends = ['davidhalter/jedi-vim']

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'ompugao/ros.vim'
